name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install tools
        run: |
          pacman -Syu --noconfirm --needed \
            git \
            python \
            python-pytest \
            qt6-declarative \
            shellcheck
      - uses: actions/checkout@v7
      - name: Run checks
        run: ./scripts/check.sh
